<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20261002072846 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Échéances mensuelles des baux et début du suivi des loyers';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE rent_due (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, period DATE NOT NULL, due_date DATE NOT NULL, rent INT NOT NULL, charges INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, lease_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_rent_due_lease_period ON rent_due (lease_id, period)');
        $this->addSql('CREATE INDEX IDX_DF55668FD3CA542C ON rent_due (lease_id)');
        $this->addSql('ALTER TABLE rent_due ADD CONSTRAINT FK_DF55668FD3CA542C FOREIGN KEY (lease_id) REFERENCES lease (id) NOT DEFERRABLE');
        // Colonne obligatoire ajoutée à une table qui contient déjà des baux : on l'ajoute vide,
        // on la remplit (suivi depuis le début du bail), puis on la rend obligatoire.
        $this->addSql('ALTER TABLE lease ADD rent_tracked_from DATE DEFAULT NULL');
        $this->addSql("UPDATE lease SET rent_tracked_from = date_trunc('month', start_date)::date");
        $this->addSql('ALTER TABLE lease ALTER rent_tracked_from SET NOT NULL');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE rent_due DROP CONSTRAINT FK_DF55668FD3CA542C');
        $this->addSql('DROP TABLE rent_due');
        $this->addSql('ALTER TABLE lease DROP rent_tracked_from');
    }
}
