<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20261002082544 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Paiements des échéances, état et montant encaissé';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE payment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, amount INT NOT NULL, paid_on DATE NOT NULL, method VARCHAR(20) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, rent_due_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6D28840DA48EF008 ON payment (rent_due_id)');
        $this->addSql('ALTER TABLE payment ADD CONSTRAINT FK_6D28840DA48EF008 FOREIGN KEY (rent_due_id) REFERENCES rent_due (id) NOT DEFERRABLE');
        // Les échéances existantes n'ont reçu aucun paiement : la valeur par défaut sert à les remplir,
        // puis elle est retirée (c'est l'application qui fixe ces valeurs à la création d'une échéance).
        $this->addSql("ALTER TABLE rent_due ADD status VARCHAR(20) DEFAULT 'unpaid' NOT NULL");
        $this->addSql('ALTER TABLE rent_due ALTER status DROP DEFAULT');
        $this->addSql('ALTER TABLE rent_due ADD paid_amount INT DEFAULT 0 NOT NULL');
        $this->addSql('ALTER TABLE rent_due ALTER paid_amount DROP DEFAULT');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE payment DROP CONSTRAINT FK_6D28840DA48EF008');
        $this->addSql('DROP TABLE payment');
        $this->addSql('ALTER TABLE rent_due DROP status');
        $this->addSql('ALTER TABLE rent_due DROP paid_amount');
    }
}
