<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20261002070738 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Baux et locataires';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE lease (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, start_date DATE NOT NULL, rent INT NOT NULL, charges INT NOT NULL, deposit INT NOT NULL, payment_day SMALLINT NOT NULL, furnished BOOLEAN NOT NULL, irl_reference_quarter SMALLINT NOT NULL, irl_reference_year SMALLINT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, property_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E6C77495549213EC ON lease (property_id)');
        $this->addSql('CREATE TABLE tenant (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, first_name VARCHAR(100) NOT NULL, last_name VARCHAR(100) NOT NULL, email VARCHAR(180) NOT NULL, lease_id INT NOT NULL, user_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_4E59C462D3CA542C ON tenant (lease_id)');
        $this->addSql('CREATE INDEX IDX_4E59C462A76ED395 ON tenant (user_id)');
        $this->addSql('ALTER TABLE lease ADD CONSTRAINT FK_E6C77495549213EC FOREIGN KEY (property_id) REFERENCES property (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE tenant ADD CONSTRAINT FK_4E59C462D3CA542C FOREIGN KEY (lease_id) REFERENCES lease (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE tenant ADD CONSTRAINT FK_4E59C462A76ED395 FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE lease DROP CONSTRAINT FK_E6C77495549213EC');
        $this->addSql('ALTER TABLE tenant DROP CONSTRAINT FK_4E59C462D3CA542C');
        $this->addSql('ALTER TABLE tenant DROP CONSTRAINT FK_4E59C462A76ED395');
        $this->addSql('DROP TABLE lease');
        $this->addSql('DROP TABLE tenant');
    }
}
